// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(ParkingManagementContext))]
    [Migration("20220602124117_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Persistence.DataModel.BillChargesData", b =>
                {
                    b.Property<Guid>("BillChargeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChargeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("ChargedAmount")
                        .HasColumnType("float");

                    b.Property<int>("Hours")
                        .HasColumnType("int");

                    b.HasKey("BillChargeId");

                    b.HasIndex("ChargeId");

                    b.HasIndex("BillId", "ChargeId")
                        .IsUnique();

                    b.ToTable("BillCharges");
                });

            modelBuilder.Entity("Persistence.DataModel.BillsData", b =>
                {
                    b.Property<Guid>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AllottingTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TotalBillableHours")
                        .HasColumnType("int");

                    b.Property<double?>("TotalCharges")
                        .HasColumnType("float");

                    b.Property<string>("VehicleNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BillId");

                    b.HasIndex("VehicleNumber");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("Persistence.DataModel.ChargesData", b =>
                {
                    b.Property<Guid>("ChargeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChargeDuration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChargeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ChargeValue")
                        .HasColumnType("float");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChargeId");

                    b.ToTable("Charges");
                });

            modelBuilder.Entity("Persistence.DataModel.ParkingSpotData", b =>
                {
                    b.Property<Guid>("ParkingSpotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SpotNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ParkingSpotId");

                    b.HasIndex("VehicleNumber");

                    b.ToTable("ParkingSpots");
                });

            modelBuilder.Entity("Persistence.DataModel.VehiclesData", b =>
                {
                    b.Property<string>("VehicleNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VehicleNumber");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("Persistence.DataModel.BillChargesData", b =>
                {
                    b.HasOne("Persistence.DataModel.BillsData", "Bill")
                        .WithMany("BillCharges")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Persistence.DataModel.ChargesData", "Charge")
                        .WithMany("BillCharges")
                        .HasForeignKey("ChargeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("Charge");
                });

            modelBuilder.Entity("Persistence.DataModel.BillsData", b =>
                {
                    b.HasOne("Persistence.DataModel.VehiclesData", "Vehicle")
                        .WithMany("Bills")
                        .HasForeignKey("VehicleNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Persistence.DataModel.ParkingSpotData", b =>
                {
                    b.HasOne("Persistence.DataModel.VehiclesData", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleNumber");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Persistence.DataModel.BillsData", b =>
                {
                    b.Navigation("BillCharges");
                });

            modelBuilder.Entity("Persistence.DataModel.ChargesData", b =>
                {
                    b.Navigation("BillCharges");
                });

            modelBuilder.Entity("Persistence.DataModel.VehiclesData", b =>
                {
                    b.Navigation("Bills");
                });
#pragma warning restore 612, 618
        }
    }
}
